services:
  - type: web
    name: myapp
    env: node
    plan: starter
    buildCommand: yarn; prisma migrate up --schema db/schema.prisma --create-db --experimental --auto-approve; blitz build
    startCommand: blitz start --production -H 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auth-example
          property: connectionString
